In [58]:
import matplotlib.pyplot as plt

In [59]:
import numpy as np

In [60]:
x = [1, 2, 3, 4, 5]
x = np.array(x)
x

array([1, 2, 3, 4, 5])

In [34]:
x.shape

(5,)

In [35]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
matrix[0][0]

1

In [37]:
matrix[0][2]

3

Two ways of accessing:

In [38]:
matrix[1][0]

4

In [39]:
matrix[1, 0]

4

In [40]:
x, x[1:3]

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [41]:
a = np.array(range(1, 100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
a.sum(), a.mean(), np.median(a), a.std()

(4950, 50.0, 50.0, 28.577380332470412)

In [43]:
x[x > 3]

array([4, 5])

In [44]:
evens = x[x%2 ==0]
evens

array([2, 4])

In [45]:
s = np.zeros(10)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
s + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

for the exercises:

In [47]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [48]:
negative_nums = a[a < 0]

negative_nums

array([-2, -1, -6, -7])

In [49]:
positive_nums = a[a > 0]

positive_nums

array([ 4, 10, 12, 23,  3])

In [50]:
#even_positive_nums = positive_nums % 2 == 0

even_positive_nums = positive_nums[positive_nums % 2 == 0]

even_positive_nums

array([ 4, 10, 12])

In [51]:
add_three = a + 3
np.count_nonzero
add_three, add_three % 2 == 0

(array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4]),
 array([False, False, False,  True, False,  True, False, False, False,
        False,  True,  True]))

In [52]:
num_sqrd = a ** 2

num_sqrd, num_sqrd.mean(), num_sqrd.std()

(array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49]),
 74.0,
 144.0243035046516)

In [53]:
centered = a - a.mean()

a, a.mean(), centered

(array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7]),
 3.0,
 array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
        -10.]))

In [54]:
import scipy.stats as stats 
stats.zscore(a)

# -------- OR --------------

z_score = (a - a.mean()) / a.std()
z_score

# stats.zscore(a), z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])



More Numpy Practice exercises

In [55]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#a = np.array(a)

In [56]:
#sum_of_a = a.sum()
#a.sum()



In [61]:
min_of_a = a.min()
min_of_a

AttributeError: 'list' object has no attribute 'min'

In [62]:
max_of_a = a.max()
max_of_a

AttributeError: 'list' object has no attribute 'max'

In [ ]:
mean_of_a = a.mean()
mean_of_a

In [ ]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)
b

In [ ]:
sum_of_b = b.sum()
b.sum()


In [ ]:
product_of_b = b.multiply()
product_of_b

In [ ]:
squares_of_b = b ** 2
squares_of_b

In [ ]:
odds_in_b = b[b % 2 == 1]
odds_in_b

In [ ]:
np.shape(b)

In [ ]:
b.reshape(-1)

In [ ]:
b.reshape(6, 1, -1)

In [63]:
import pandas as pd

In [64]:

numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 19, 23, 256, -8, -4, -2, 5, -9]

num_series = pd.Series(numbers)
num_series

0       2
1       3
2       4
3       5
4       6
5       7
6       8
7       9
8      10
9      11
10     13
11     17
12     19
13     23
14    256
15     -8
16     -4
17     -2
18      5
19     -9
dtype: int64

In [65]:

fruits = ['mango', 'kiwi', 'strawberry', 'guava', 'pineapple', 'mandarin orange']
fruit_series = pd.Series(fruits)
fruit_series

0              mango
1               kiwi
2         strawberry
3              guava
4          pineapple
5    mandarin orange
dtype: object

In [66]:
#1. Make a variable named uppercased_fruits 

uppercased_fruits = fruit_series.str.upper()
uppercased_fruits

0              MANGO
1               KIWI
2         STRAWBERRY
3              GUAVA
4          PINEAPPLE
5    MANDARIN ORANGE
dtype: object

In [67]:
#2. Create a variable named capitalized_fruits

capitalized_fruits = fruit_series.str.title()
capitalized_fruits

0              Mango
1               Kiwi
2         Strawberry
3              Guava
4          Pineapple
5    Mandarin Orange
dtype: object

In [68]:
#3. Make a variable named fruits_with_more_than_two_vowels

fruits_with_more_than_two_vowels
fruits_with_more_than_two_vowels

NameError: name 'fruits_with_more_than_two_vowels' is not defined

In [69]:
#4. Make a variable named fruits_with_only_two_vowels

fruits_with_only_two_vowels
fruits_with_only_two_vowels

NameError: name 'fruits_with_only_two_vowels' is not defined

In [70]:
#5 - make a list that contains each fruit with more than 5 characters

more_than_five = fruit_series[fruit_series.str.len() > 5]
more_than_five

2         strawberry
4          pineapple
5    mandarin orange
dtype: object

In [71]:
#6 - make a list that contains each fruit with exactly 5 characters

exactly_five = fruit_series[fruit_series.str.len() == 5]
exactly_five

0    mango
3    guava
dtype: object

In [72]:
#9 - Make a variable named fruits_with_letter_a that contains a list of only the fruits that contain the letter "a"

fruits_with_letter_a = fruit_series[fruit_series.in('a')]
fruits_with_letter_a

SyntaxError: invalid syntax (<ipython-input-72-0b41b48af300>, line 3)

In [73]:
#10 - Make a variable named even_numbers that holds only the even numbers 

even_numbers = num_series[num_series % 2 == 0]
even_numbers

0       2
2       4
4       6
6       8
8      10
14    256
15     -8
16     -4
17     -2
dtype: int64

In [74]:
# Exercise 11 - Make a variable named odd_numbers that holds only the odd numbers

odd_numbers = num_series[num_series % 2 != 0]
odd_numbers

1      3
3      5
5      7
7      9
9     11
10    13
11    17
12    19
13    23
18     5
19    -9
dtype: int64

In [75]:
# Exercise 12 - Make a variable named positive_numbers that holds only the positive numbers

positive_numbers = num_series[num_series > 0]
positive_numbers

0       2
1       3
2       4
3       5
4       6
5       7
6       8
7       9
8      10
9      11
10     13
11     17
12     19
13     23
14    256
18      5
dtype: int64

In [76]:
# Exercise 13 - Make a variable named negative_numbers that holds only the negative numbers

negative_numbers = num_series[num_series < 0]
negative_numbers

15   -8
16   -4
17   -2
19   -9
dtype: int64

In [88]:
numbers_squared = num_series ** 2
numbers_squared

0         4
1         9
2        16
3        25
4        36
5        49
6        64
7        81
8       100
9       121
10      169
11      289
12      361
13      529
14    65536
15       64
16       16
17        4
18       25
19       81
dtype: int64

In [97]:
odd_negative_numbers = num_series[num_series % 2 != 0] & num_series[num_series < 0]

odd_negative_numbers

1     False
3     False
5     False
7     False
9     False
10    False
11    False
12    False
13    False
15    False
16    False
17    False
18    False
19     True
dtype: bool

In [89]:
numbers_plus_5 = num_series + 5
numbers_plus_5

0       7
1       8
2       9
3      10
4      11
5      12
6      13
7      14
8      15
9      16
10     18
11     22
12     24
13     28
14    261
15     -3
16      1
17      3
18     10
19     -4
dtype: int64

In [91]:
num_series[num_series > 9]

8      10
9      11
10     13
11     17
12     19
13     23
14    256
dtype: int64

In [ ]:
fruits = ["kiwi", "mango", "strawberry", "pineapple", "gala apple", "honeycrisp apple", "tomato", "watermelon", "honeydew", "kiwi", "kiwi", "kiwi", "mango", "blueberry", "blackberry", "gooseberry", "papaya"]
fruits_series = pd.Series(fruits)
fruits_series

In [ ]:
fruits_series.describe()

In [ ]:
fruits_series.unique()

In [ ]:
fruits_series.value_counts()

In [ ]:
longest_str = fruits_series.str.len().max()
longest_str

In [ ]:
five_or_more = fruits_series[fruits_series.str.len() > 5]
five_or_more

In [ ]:
cash = ['$796,459.41', '$278.60', '$482,571.67', '$4,503,915.98', '$2,121,418.3', '$1,260,813.3', '$87,231.01', '$1,509,175.45', '$4,138,548.00', '$2,848,913.80', '$594,715.39', '$4,789,988.17', '$4,513,644.5', '$3,191,059.97', '$1,758,712.24', '$4,338,283.54', '$4,738,303.38', '$2,791,759.67', '$769,681.94', '$452,650.23']
cash_series = pd.Series(cash)
cash_series

In [ ]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]


In [ ]:
np.tan(d)

In [ ]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)

In [ ]:
(c * c.T).sum()

In [ ]:
(c * c.T).prod()

In [ ]:
fruits_series[(fruits_series.str.count(r'[aeiou]')).max()]

In [ ]:
float_num = cash_series.str.replace('$', '').str.replace(',', '').astype('float')
float_num

In [ ]:
float_num.max()

In [ ]:
float_num.value_counts(bins=4).sort_index(ascending=False).plot.barh(ec = 'black', 
                                                                    color= 'slateblue',  
                                                                    width = .8)

plt.title('Cash Values')
plt.xlabel('Count')
plt.ylabel('US $')
plt.show()

In [ ]:
exams  = [60, 86, 75, 62, 93, 71, 60, 83, 95, 78, 65, 72, 69, 81, 96, 80, 85, 92, 82, 78]
exam_series = pd.Series(exams)
exam_series


In [ ]:
exam_series.plot.hist(color='seagreen',
                     ec='black')
                     

plt.title('Score Distribution')
plt.xlabel('Scores')
plt.show()

In [ ]:
curve = 100 - exam_series.max()
curve

In [ ]:

string = 'hnvidduckkqxwymbimkccexbkmqygkxoyndmcxnwqarhyffsjpsrabtjzsypmzadfavyrnndndvswreauxovncxtwzpwejilzjrmmbbgbyxvjtewqthafnbkqplarokkyydtubbmnexoypulzwfhqvckdpqtpoppzqrmcvhhpwgjwupgzhiofohawytlsiyecuproguy'


In [ ]:
letters_list = ' '.join(string).split(' ')

In [ ]:
letters = pd.Series(letters_list)
letters.head()

In [166]:

letters.value_counts().head(7).plot.barh(color='royalblue',
                                        ec='black',
                                        width=.8)
    
plt.title('Most Frequently Occuring Letters')

# I wanted the most frequent letter at the top, so I chose to invert the y-axis.
plt.gca().invert_yaxis()

plt.show()

NameError: name 'letters' is not defined

In [98]:
from pydataset import data

In [99]:
# data('mpg', show_doc=True) # view the documentation for the dataset
mpg = data('mpg') # load the dataset and store it in a variable

In [100]:
data('mpg', show_doc=True) 

mpg

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Fuel economy data from 1999 and 2008 for 38 popular models of car

### Description

This dataset contains a subset of the fuel economy data that the EPA makes
available on http://fueleconomy.gov. It contains only models which had a new
release every year between 1999 and 2008 - this was used as a proxy for the
popularity of the car.

### Usage

    data(mpg)

### Format

A data frame with 234 rows and 11 variables

### Details

  * manufacturer. 

  * model. 

  * displ. engine displacement, in litres 

  * year. 

  * cyl. number of cylinders 

  * trans. type of transmission 

  * drv. f = front-wheel drive, r = rear wheel drive, 4 = 4wd 

  * cty. city miles per gallon 

  * hwy. highway miles per gallon 

  * fl. 

  * class. 




In [102]:
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [103]:
mpg.tail()

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize

In [104]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
manufacturer    234 non-null object
model           234 non-null object
displ           234 non-null float64
year            234 non-null int64
cyl             234 non-null int64
trans           234 non-null object
drv             234 non-null object
cty             234 non-null int64
hwy             234 non-null int64
fl              234 non-null object
class           234 non-null object
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [106]:
mpg.describe()

displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

In [108]:
mpg.rename(columns = {'cty': 'city', 'hwy': 'highway'}, inplace=True)
mpg.columns

Index(['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'city',
       'highway', 'fl', 'class'],
      dtype='object')

In [109]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
manufacturer    234 non-null object
model           234 non-null object
displ           234 non-null float64
year            234 non-null int64
cyl             234 non-null int64
trans           234 non-null object
drv             234 non-null object
city            234 non-null int64
highway         234 non-null int64
fl              234 non-null object
class           234 non-null object
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [138]:
mpg['mileage_difference'] = mpg['highway'] - mpg['city']
mpg.head()

manufacturer model  displ  year  cyl       trans drv  city  highway fl  \
1         audi    a4    1.8  1999    4    auto(l5)   f    18       29  p   
2         audi    a4    1.8  1999    4  manual(m5)   f    21       29  p   
3         audi    a4    2.0  2008    4  manual(m6)   f    20       31  p   
4         audi    a4    2.0  2008    4    auto(av)   f    21       30  p   
5         audi    a4    2.8  1999    6    auto(l5)   f    16       26  p   

     class  mileage_difference  
1  compact                  11  
2  compact                   8  
3  compact                  11  
4  compact                   9  
5  compact                  10

In [111]:
np.random.seed(123)

students = ['Sally', 'Jane', 'Suzie', 'Billy', 'Ada', 'John', 'Thomas',
            'Marie', 'Albert', 'Richard', 'Isaac', 'Alan']

# randomly generate scores for each student for each subject
# note that all the values need to have the same length here
math_grades = np.random.randint(low=60, high=100, size=len(students))
english_grades = np.random.randint(low=60, high=100, size=len(students))
reading_grades = np.random.randint(low=60, high=100, size=len(students))

df = pd.DataFrame({'name': students,
                   'math': math_grades,
                   'english': english_grades,
                   'reading': reading_grades})


In [120]:
df['passing_english'] = df.english > 70

In [121]:
df.sort_values(by='passing_english')

name  math  english  reading  passing_english
6    Thomas    82       64       81            False
7     Marie    93       63       90            False
8    Albert    92       62       87            False
11     Alan    92       62       72            False
0     Sally    62       85       80             True
1      Jane    88       79       67             True
2     Suzie    94       74       95             True
3     Billy    98       96       88             True
4       Ada    77       92       98             True
5      John    79       76       93             True
9   Richard    69       80       94             True
10    Isaac    92       99       93             True

In [124]:
df.sort_values(by = ['passing_english', 'name'])


name  math  english  reading  passing_english
11     Alan    92       62       72            False
8    Albert    92       62       87            False
7     Marie    93       63       90            False
6    Thomas    82       64       81            False
4       Ada    77       92       98             True
3     Billy    98       96       88             True
10    Isaac    92       99       93             True
1      Jane    88       79       67             True
5      John    79       76       93             True
9   Richard    69       80       94             True
0     Sally    62       85       80             True
2     Suzie    94       74       95             True

In [125]:
df.sort_values(by = ['passing_english', 'english'])

name  math  english  reading  passing_english
8    Albert    92       62       87            False
11     Alan    92       62       72            False
7     Marie    93       63       90            False
6    Thomas    82       64       81            False
2     Suzie    94       74       95             True
5      John    79       76       93             True
1      Jane    88       79       67             True
9   Richard    69       80       94             True
0     Sally    62       85       80             True
4       Ada    77       92       98             True
3     Billy    98       96       88             True
10    Isaac    92       99       93             True

In [126]:
df['overall_grade'] = df['math'] + df['english'] + df['reading'] / 3

In [127]:
df

name  math  english  reading  passing_english  overall_grade
0     Sally    62       85       80             True     173.666667
1      Jane    88       79       67             True     189.333333
2     Suzie    94       74       95             True     199.666667
3     Billy    98       96       88             True     223.333333
4       Ada    77       92       98             True     201.666667
5      John    79       76       93             True     186.000000
6    Thomas    82       64       81            False     173.000000
7     Marie    93       63       90            False     186.000000
8    Albert    92       62       87            False     183.000000
9   Richard    69       80       94             True     180.333333
10    Isaac    92       99       93             True     222.000000
11     Alan    92       62       72            False     178.000000

In [128]:
#Do any cars have better city mileage than highway mileage?

mpg.head()

manufacturer model  displ  year  cyl       trans drv  city  highway fl  \
1         audi    a4    1.8  1999    4    auto(l5)   f    18       29  p   
2         audi    a4    1.8  1999    4  manual(m5)   f    21       29  p   
3         audi    a4    2.0  2008    4  manual(m6)   f    20       31  p   
4         audi    a4    2.0  2008    4    auto(av)   f    21       30  p   
5         audi    a4    2.8  1999    6    auto(l5)   f    16       26  p   

     class  mileage_difference  
1  compact                  11  
2  compact                   8  
3  compact                  11  
4  compact                   9  
5  compact                  10

In [132]:
# mpg[mpg.city > mpg.highway]
mpg.sort_values(by=mileage_difference <= 0]

Empty DataFrame
Columns: [manufacturer, model, displ, year, cyl, trans, drv, city, highway, fl, class, mileage_difference]
Index: []

In [142]:
#h Which car (or cars) has the highest mileage difference?

mpg.sort_values(by='mileage_difference', ascending=False)

manufacturer              model  displ  year  cyl       trans drv  city  \
107        honda              civic    1.8  2008    4    auto(l5)   f    24   
223   volkswagen         new beetle    1.9  1999    4    auto(l4)   f    29   
1           audi                 a4    1.8  1999    4    auto(l5)   f    18   
229   volkswagen             passat    1.8  1999    4    auto(l5)   f    18   
36     chevrolet             malibu    3.5  2008    6    auto(l4)   f    18   
..           ...                ...    ...   ...  ...         ...  ..   ...   
80          ford       explorer 4wd    4.0  1999    6    auto(l5)   4    14   
138      mercury    mountaineer 4wd    4.0  1999    6    auto(l5)   4    14   
177       toyota        4runner 4wd    3.4  1999    6  manual(m5)   4    15   
152       nissan     pathfinder 4wd    3.3  1999    6  manual(m5)   4    15   
204       toyota  toyota tacoma 4wd    3.4  1999    6  manual(m5)   4    15   

     highway fl       class  mileage_difference  
107       36  c  subcompact                  12  
223       41  d  subcompact                  12  
1         29  p     compact                  11  
229       29  p     midsize                  11  
36        29  r     midsize                  11  
..       ... ..         ...                 ...  
80        17  r         suv                   3  
138       17  r         suv                   3  
177       17  r         suv                   2  
152       17  r         suv                   2  
204       17  r      pickup                   2  

[234 rows x 12 columns]

In [143]:
#i Which compact class car has the lowest highway mileage? The best?

mpg.sort_values(by='mileage_difference', ascending=False) & (mpg.class == 'compact')
#df[(df.wins > 7) | (df.losses < 4)]

SyntaxError: invalid syntax (<ipython-input-143-36dfd14cafbf>, line 3)

In [144]:
mpg['average_mileage'] = (mpg['highway'] + mpg['city']) / 2
mpg.head()


manufacturer model  displ  year  cyl       trans drv  city  highway fl  \
1         audi    a4    1.8  1999    4    auto(l5)   f    18       29  p   
2         audi    a4    1.8  1999    4  manual(m5)   f    21       29  p   
3         audi    a4    2.0  2008    4  manual(m6)   f    20       31  p   
4         audi    a4    2.0  2008    4    auto(av)   f    21       30  p   
5         audi    a4    2.8  1999    6    auto(l5)   f    16       26  p   

     class  mileage_difference  average_mileage  
1  compact                  11             23.5  
2  compact                   8             25.0  
3  compact                  11             25.5  
4  compact                   9             25.5  
5  compact                  10             21.0

In [150]:
mammals = data('Mammals')

In [151]:
mammals.head()

weight  speed  hoppers  specials
1  6000.0   35.0    False     False
2  4000.0   26.0    False     False
3  3000.0   25.0    False     False
4  1400.0   45.0    False     False
5   400.0   70.0    False     False

In [152]:
mammals.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 107 entries, 1 to 107
Data columns (total 4 columns):
weight      107 non-null float64
speed       107 non-null float64
hoppers     107 non-null bool
specials    107 non-null bool
dtypes: bool(2), float64(2)
memory usage: 2.7 KB


In [153]:
mammals.describe()

weight       speed
count   107.000000  107.000000
mean    278.688178   46.208411
std     839.608269   26.716778
min       0.016000    1.600000
25%       1.700000   22.500000
50%      34.000000   48.000000
75%     142.500000   65.000000
max    6000.000000  110.000000

In [156]:
mammals.sort_values(by = 'speed', ascending=False).head()
#df.sort_values(by='passing_english')

weight  speed  hoppers  specials
53    55.0  110.0    False     False
39    37.0  105.0    False     False
35    50.0  100.0    False     False
41    34.0   97.0    False     False
42    30.0   97.0    False     False

In [164]:
# mammals[('hoppers' == True) & (mammals.speed > np.median(mammals.speed))]
mammals[(mammals.hoppers == True) & (mammals.speed > np.median(mammals.speed))]

weight  speed  hoppers  specials
96      4.6   64.0     True     False
97      4.4   72.0     True     False
98      4.0   72.0     True     False
99      3.5   56.0     True     False
100     2.0   64.0     True     False
101     1.9   56.0     True     False
102     1.5   50.0     True     False

In [165]:
bool_series = mpg['class'] == 'compact'
compacts = mpg[bool_series]
compacts.nsmallest(1, 'highway', keep='all')

manufacturer  model  displ  year  cyl     trans drv  city  highway fl  \
220   volkswagen  jetta    2.8  1999    6  auto(l4)   f    16       23  r   

       class  mileage_difference  average_mileage  
220  compact                   7             19.5

In [170]:
#df.loc[:, 'math': 'reading'].sum(axis=1)
df['overall_grade'] = round(df.loc[:, 'math': 'reading'].sum(axis=1) / 3)

In [171]:
df

name  math  english  reading  passing_english  overall_grade
0     Sally    62       85       80             True           76.0
1      Jane    88       79       67             True           78.0
2     Suzie    94       74       95             True           88.0
3     Billy    98       96       88             True           94.0
4       Ada    77       92       98             True           89.0
5      John    79       76       93             True           83.0
6    Thomas    82       64       81            False           76.0
7     Marie    93       63       90            False           82.0
8    Albert    92       62       87            False           80.0
9   Richard    69       80       94             True           81.0
10    Isaac    92       99       93             True           95.0
11     Alan    92       62       72            False           75.0

In [173]:
mpg.head()

manufacturer model  displ  year  cyl       trans drv  city  highway fl  \
1         audi    a4    1.8  1999    4    auto(l5)   f    18       29  p   
2         audi    a4    1.8  1999    4  manual(m5)   f    21       29  p   
3         audi    a4    2.0  2008    4  manual(m6)   f    20       31  p   
4         audi    a4    2.0  2008    4    auto(av)   f    21       30  p   
5         audi    a4    2.8  1999    6    auto(l5)   f    16       26  p   

     class  mileage_difference  average_mileage  
1  compact                  11             23.5  
2  compact                   8             25.0  
3  compact                  11             25.5  
4  compact                   9             25.5  
5  compact                  10             21.0

In [175]:
mpg.drop(columns=['displ', 'drv', 'fl'])


manufacturer   model  year  cyl       trans  city  highway    class  \
1           audi      a4  1999    4    auto(l5)    18       29  compact   
2           audi      a4  1999    4  manual(m5)    21       29  compact   
3           audi      a4  2008    4  manual(m6)    20       31  compact   
4           audi      a4  2008    4    auto(av)    21       30  compact   
5           audi      a4  1999    6    auto(l5)    16       26  compact   
..           ...     ...   ...  ...         ...   ...      ...      ...   
230   volkswagen  passat  2008    4    auto(s6)    19       28  midsize   
231   volkswagen  passat  2008    4  manual(m6)    21       29  midsize   
232   volkswagen  passat  1999    6    auto(l5)    16       26  midsize   
233   volkswagen  passat  1999    6  manual(m5)    18       26  midsize   
234   volkswagen  passat  2008    6    auto(s6)    17       26  midsize   

     mileage_difference  average_mileage  
1                    11             23.5  
2                     8             25.0  
3                    11             25.5  
4                     9             25.5  
5                    10             21.0  
..                  ...              ...  
230                   9             23.5  
231                   8             25.0  
232                  10             21.0  
233                   8             22.0  
234                   9             21.5  

[234 rows x 10 columns]

In [182]:
mpg['manufacturer'].value_counts()

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64

In [198]:
mpg['manufacturer'].nunique()

15

In [199]:
mpg['model'].nunique()

38

In [194]:
mpg.loc[mpg['average_mileage'] > 34]

manufacturer       model  displ  year  cyl       trans drv  city  highway  \
213   volkswagen       jetta    1.9  1999    4  manual(m5)   f    33       44   
222   volkswagen  new beetle    1.9  1999    4  manual(m5)   f    35       44   
223   volkswagen  new beetle    1.9  1999    4    auto(l4)   f    29       41   

    fl       class  mileage_difference  average_mileage  
213  d     compact                  11             38.5  
222  d  subcompact                   9             39.5  
223  d  subcompact                  12             35.0

In [197]:
mpg.sort_values(by = 'average_mileage', ascending=False).head()

manufacturer       model  displ  year  cyl       trans drv  city  highway  \
222   volkswagen  new beetle    1.9  1999    4  manual(m5)   f    35       44   
213   volkswagen       jetta    1.9  1999    4  manual(m5)   f    33       44   
223   volkswagen  new beetle    1.9  1999    4    auto(l4)   f    29       41   
197       toyota     corolla    1.8  2008    4  manual(m5)   f    28       37   
196       toyota     corolla    1.8  1999    4  manual(m5)   f    26       35   

    fl       class  mileage_difference  average_mileage  
222  d  subcompact                   9             39.5  
213  d     compact                  11             38.5  
223  d  subcompact                  12             35.0  
197  r     compact                   9             32.5  
196  r     compact                   9             30.5

In [201]:
#d. Do automatic or manual cars have better miles per gallon?
mpg.sort_values(by = 'trans', ascending=False)

manufacturer                model  displ  year  cyl       trans drv  city  \
24     chevrolet             corvette    5.7  1999    8  manual(m6)   r    16   
15          audi           a4 quattro    3.1  2008    6  manual(m6)   4    15   
146       nissan               altima    3.5  2008    6  manual(m6)   f    19   
145       nissan               altima    2.5  2008    4  manual(m6)   f    23   
65         dodge  ram 1500 pickup 4wd    4.7  2008    8  manual(m6)   4    12   
..           ...                  ...    ...   ...  ...         ...  ..   ...   
150       nissan               maxima    3.5  2008    6    auto(av)   f    19   
147       nissan               altima    3.5  2008    6    auto(av)   f    19   
7           audi                   a4    3.1  2008    6    auto(av)   f    18   
144       nissan               altima    2.5  2008    4    auto(av)   f    23   
4           audi                   a4    2.0  2008    4    auto(av)   f    21   

     highway fl    class  mileage_difference  average_mileage  
24        26  p  2seater                  10             21.0  
15        25  p  compact                  10             20.0  
146       27  p  midsize                   8             23.0  
145       32  r  midsize                   9             27.5  
65        16  r   pickup                   4             14.0  
..       ... ..      ...                 ...              ...  
150       25  p  midsize                   6             22.0  
147       26  p  midsize                   7             22.5  
7         27  p  compact                   9             22.5  
144       31  r  midsize                   8             27.0  
4         30  p  compact                   9             25.5  

[234 rows x 13 columns]